Repository universal-ember/kolay, pull requests merged in 2024-07, with the labels that each got.

#86 Fix app watching -- Copy content from #82
  docs-app/ember-cli-build.js
  docs-app/package.json
  pnpm-lock.yaml
Labels: internal

#84 Consider 4xx and 5xx status as error instead of trying to render MD
  .eslintrc.cjs
  docs-app/app/templates/page.gjs
  docs-app/public/docs/plugins/kolay.md
  docs-app/public/docs/usage/rendering-pages.md
  docs-app/tests/docs-app/errors-test.gts
  package.json
  ui/package.json
  ui/src/services/kolay/docs.ts
  ui/src/services/kolay/request.ts
  ui/src/services/kolay/selected.ts
Labels: bug

#93 Fix setup.md instructions to match the need to pass `this`, and updat…
  docs-app/public/docs/usage/setup.md
Labels: documentation

#91 Throw Errors When Meta Order Does Not Match Available Pages
  docs-app/public/docs/meta.jsonc
  docs-app/public/docs/usage/meta.jsonc
  fixtures/discover/c/index.md
  fixtures/discover/c/meta.jsonc
  fixtures/discover/meta.jsonc
  package.json
  src/plugins/markdown-pages/discover.test.ts
  src/plugins/markdown-pages/sort.applyPredestinedOrder.test.ts
  src/plugins/markdown-pages/sort.js
  src/plugins/markdown-pages/sort.sortTree.test.ts
Labels: enhancement

#94 Fix support for referencing modifiers with ember-modifier 4.2 (and ember-modifier 4.1)
  docs-app/package.json
  package.json
  pnpm-lock.yaml
  src/plugins/api-docs/typedoc.js
  src/plugins/helpers.extractExports.test.ts
  src/plugins/helpers.extractTypesVersions.test.ts
  src/plugins/helpers.js
  ui/package.json
Labels: bug

#96 Fix Hash and other URL oddities: Use URL parsing instead of bespoke regex
  docs-app/tests/docs-app/errors-test.gts
  ui/src/services/kolay/selected.ts
Labels: bug

#101 Fixes Configs Not Found In Dasherized Paths
  src/plugins/markdown-pages/discover.test.ts
  src/plugins/markdown-pages/hydrate.addInTheFirstPage.test.ts
  src/plugins/markdown-pages/hydrate.prefixPaths.test.ts
  src/plugins/markdown-pages/parse.build.test.ts
  src/plugins/markdown-pages/parse.js
  src/plugins/markdown-pages/sort.js
  src/plugins/markdown-pages/sort.sortTree.test.ts
  ui/src/services/kolay/types.ts
Labels: bug

#105 Make sure to .trim() the group names after cleaning
  src/plugins/markdown-pages/parse.build.test.ts
  src/plugins/markdown-pages/parse.js
Labels: bug

#103 Fix implicit sorting (sorting based on file path)
  src/plugins/markdown-pages/discover.test.ts
  src/plugins/markdown-pages/parse.build.test.ts
  src/plugins/markdown-pages/parse.js
  src/plugins/markdown-pages/sort.betterSort.test.ts
  src/plugins/markdown-pages/sort.js
Labels: bug

#106 Allow packages to be unspecified
  src/plugins/combined.js
Labels: bug

#107 Widen range on the UI library
  package.json
  pnpm-lock.yaml
Labels: bug

#109 Add type-narrowing utilities for working with the manifest's tree's pages vs collections
  src/plugins/markdown-pages/sort.betterSort.test.ts
  ui/src/components/page-nav.gts
  ui/src/index.ts
  ui/src/utils.ts
Labels: enhancement

#111 Don't use the workspace protocol for the peer range
  package.json
Labels: bug

#113 Fix selected service service-registry entry
  ui/src/services/kolay/selected.ts
Labels: bug
