Repository universal-ember/kolay, pull requests merged in 2025-05, with the labels that each got.

#187 Remove unneeded peerDependencies (provided by ember-source virtualDeps)
  package.json
  pnpm-lock.yaml
Labels: bug

#189 Update release-plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  RELEASE.md
  package.json
Labels: internal

#191 Update deps
  docs-app/package.json
  package.json
  pnpm-lock.yaml
Labels: enhancement

#192 Bump ember-primitives
  package.json
  pnpm-lock.yaml
Labels: bug

#194 Fix release
  .github/workflows/publish.yml
  README.md
Labels: bug

#196 support custom base url for vite
  docs-app/package.json
  docs-app/src/app.ts
  docs-app/src/setup-inspector.ts
  docs-app/tests/docs-app/all-links-test.gts
  docs-app/tests/kolay/components/component-signature-test.gts
  docs-app/tests/kolay/components/helper-signature-test.gts
  pnpm-lock.yaml
  src/browser/services/kolay/selected.ts
  src/build/plugins/api-docs/index.js
  src/build/plugins/api-docs/typedoc.js
  src/build/plugins/markdown-pages/markdown-pages.js
Labels: enhancement

#198 remove debug output
  src/build/plugins/api-docs/typedoc.js
Labels: bug

#202 remove everything before docs as well to detect if page exists
  src/browser/services/kolay/request.ts
Labels: bug
